#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import zasbackup,argparse,subprocess

parser = argparse.ArgumentParser(description="ZFS Auto Snapshot Auto Backup")
parser.add_argument('-a','--autorun',action='store_true')
parser.add_argument('ldn',type=str)
parser.add_argument('rdn',type=str)
parser.add_argument('rcommand',type=str)
args = parser.parse_args()

rcommand = args.rcommand.split()



l = zasbackup.Local()
r = zasbackup.Remote(rcommand)
b = zasbackup.Backup(l,r)

send,recv = b.generate(args.ldn,args.rdn,rcommand)


if send and recv:
  if not args.autorun:print("#dry-run")
  print(" ".join(send)+" | "+" ".join(recv))

  if args.autorun:
    p1 = subprocess.Popen(send, stdout=subprocess.PIPE)
    p2 = subprocess.Popen(recv, stdin=p1.stdout)
    p1.stdout.close()
    p2.communicate()
